export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAIL = 'ALL_ROOMS_FAIL';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL';

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';

export const ELIGIBLE_REVIEWER_REQUEST = 'ELIGIBLE_REVIEWER_REQUEST';
export const ELIGIBLE_REVIEWER_SUCCESS = 'ELIGIBLE_REVIEWER_SUCCESS';
export const ELIGIBLE_REVIEWER_FAIL = 'ELIGIBLE_REVIEWER_FAIL';

export const ADMIN_ROOM_REQUEST = 'ADMIN_ROOM_REQUEST';
export const ADMIN_ROOM_SUCCESS = 'ADMIN_ROOM_SUCCESS';
export const ADMIN_ROOM_FAIL = 'ADMIN_ROOM_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
