export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAIL = 'ALL_ROOMS_FAIL';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL';

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';

export const ELIGIBLE_REVIEWER_REQUEST = 'ELIGIBLE_REVIEWER_REQUEST';
export const ELIGIBLE_REVIEWER_SUCCESS = 'ELIGIBLE_REVIEWER_SUCCESS';
export const ELIGIBLE_REVIEWER_FAIL = 'ELIGIBLE_REVIEWER_FAIL';

export const ADMIN_ROOM_REQUEST = 'ADMIN_ROOM_REQUEST';
export const ADMIN_ROOM_SUCCESS = 'ADMIN_ROOM_SUCCESS';
export const ADMIN_ROOM_FAIL = 'ADMIN_ROOM_FAIL';

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_RESET = 'CREATE_ROOM_RESET';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';

export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_RESET = 'UPDATE_ROOM_RESET';
export const UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL';

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_RESET = 'DELETE_ROOM_RESET';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL';

export const REMOVE_REVIEW_REQUEST = 'REMOVE_REVIEW_REQUEST';
export const REMOVE_REVIEW_SUCCESS = 'REMOVE_REVIEW_SUCCESS';
export const REMOVE_REVIEW_RESET = 'REMOVE_REVIEW_RESET';
export const REMOVE_REVIEW_FAIL = 'REMOVE_REVIEW_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
